plugins {
	id 'java-library'
	id 'maven-publish'
	id 'net.neoforged.moddev' version '2.0.141'
	id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
	distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
	srcDir('src/generated/resources')
	exclude("src/generated/resources/.cache")
}

repositories {

	//REGISTRATE
	maven { url = "https://maven.gegy.dev/releases" }

	//CREATE
	maven { url = "https://maven.createmod.net" }
	maven { url = "https://maven.ithundxr.dev/snapshots" }

	//CC-TWEAKED
	maven {
		url = "https://maven.squiddev.cc"
		content {
			includeGroup("cc.tweaked")
		}
	}

	//JEI
	maven {
		name = "Jared's maven"
		url = "https://maven.blamejared.com/"
	}
	maven {
		name = "ModMaven"
		url = "https://modmaven.dev"
	}

	//JADE
	maven { url = "https://api.modrinth.com/maven" }

	//GECKOLIB
	//maven {
	//	name = 'GeckoLib'
	//	url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
	//	content {
	//		includeGroup("software.bernie.geckolib")
	//	}
	//}
}

base {
	archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

ext.clearLogs = {
	delete fileTree('run/logs').include('**/*gz')
	delete 'run/logs/telemetry'
}

neoForge {
	version = project.neo_version

	parchment {
		mappingsVersion = project.parchment_mappings_version
		minecraftVersion = project.parchment_minecraft_version
	}

	runs {
		clientAuth {
			clearLogs()
			client()
			if ("${world}" != '') programArguments.addAll('--quickPlaySingleplayer', "${world}")
			devLogin = true
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		client {
			clearLogs()
			client()
			if ("${world}" != '') programArguments.addAll('--quickPlaySingleplayer', "${world}")
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		server {
			clearLogs()
			server()
			programArgument '--nogui'
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		gameTestServer {
			type = "gameTestServer"
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		data {
			clearLogs()
			data()
			programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
		}

		configureEach {
			systemProperty 'forge.logging.markers', 'REGISTRIES'
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}

	mods {
		"${mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

dependencies {

	//REGISTRATE
	jarJar(api("com.tterrag.registrate:Registrate:$registrate_version"))

	//CREATE
	implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
	implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
	compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
	runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
	
	//CC-TWEAKED
	compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-forge-api:${cct_version}")
	runtimeOnly("cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cct_version}")

	//JEI
	compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
	runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

	//JADE
	implementation("maven.modrinth:jade:${jade_version}")

	//GECKOLIB
	//implementation "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}