///////////////////////////
// CONFIGURED FOR VSCODE //
///////////////////////////

plugins {
	id 'java-library'
	id 'net.neoforged.moddev' version '2.0.146'
}

tasks.named('wrapper', Wrapper).configure {
	distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
	srcDir('src/generated/resources')
	exclude('src/generated/resources/.cache')
}

tasks.named('processResources') {
	duplicatesStrategy = DuplicatesStrategy.WARN
}

tasks.register('clearLogs') {
	group = 'Utils'
	delete fileTree('run/logs').include('**/*gz')
	delete 'run/logs/telemetry'
	doLast {
		println('Logs Cleared...')
	}
}

repositories {

	//REGISTRATE
	maven { url = "https://maven.gegy.dev/releases" }

	//CREATE
	maven { url = "https://maven.createmod.net" }
	maven { url = "https://maven.ithundxr.dev/snapshots" }

	//CC-TWEAKED
	maven {
		url = "https://maven.squiddev.cc"
		content {
			includeGroup("cc.tweaked")
		}
	}

	//JEI
	maven {
		name = "Jared's maven"
		url = "https://maven.blamejared.com/"
	}
	maven {
		name = "ModMaven"
		url = "https://modmaven.dev"
	}

	//JADE
	maven { url = "https://api.modrinth.com/maven" }

	//GECKOLIB
	maven {
		name = 'GeckoLib'
		url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
		content {
			includeGroup("software.bernie.geckolib")
		}
	}
}

base {
	archivesName = mod_id
}
 
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

def devLoginProperty = providers.gradleProperty("dev_login").map{ it.toBoolean() }.orElse(false)
def quickPlayProperty = providers.gradleProperty("quick_play").orElse("")

neoForge {
	version = project.neo_version

	parchment {
		mappingsVersion = project.parchment_mappings_version
		minecraftVersion = project.parchment_minecraft_version
	}

	runs {

		client {
			client()
			devLogin = devLoginProperty.get()
			if (quickPlayProperty.get()) programArguments.addAll('--quickPlaySingleplayer', quickPlayProperty.get())
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		server {
			server()
			programArgument '--nogui'
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		gameTestServer {
			type = "gameTestServer"
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		data {
			data()
			programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
		}

		configureEach {
			disableIdeRun()
			systemProperty 'forge.logging.markers', 'REGISTRIES'
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}

	mods {
		"${mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

def useGeckolibProperty = providers.gradleProperty("use_geckolib").map{ it.toBoolean() }.orElse(false)

dependencies {

	//REGISTRATE
	jarJar(api("com.tterrag.registrate:Registrate:$registrate_version"))

	//CREATE
	implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
	implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
	compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
	runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
	
	//CC-TWEAKED
	compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-forge-api:${cct_version}")
	runtimeOnly("cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cct_version}")

	//JEI
	compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
	runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

	//JADE
	implementation("maven.modrinth:jade:${jade_version}")

	//GECKOLIB
	if (useGeckolibProperty.get()) {
		implementation "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}
