modLoader="javafml"
loaderVersion="1"
license="MIT"

[[mods]]

modId="craftory"
displayName="Craftory"
version="0.0.1"

authors="ATrueCooky"
description='''
...
'''

[[mixins]]
config="craftory.mixins.json"

[[dependencies.craftory]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.248,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.craftory]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.craftory]]
    modId="create"
    type="optional"
    versionRange="[6.0.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.craftory]]
    modId="computercraft"
    type="optional"
    versionRange="[1.120.0,)"
    ordering="NONE"
    side="BOTH"